services:
  db:
    build: db
    image: cooperps43acr.azurecr.io/db
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
    expose:
      - 5432:5432
    ports:
      - 5432:5432
    restart: always
  app:
    build: server/rps
    image: cooperps43acr.azurecr.io/app
    container_name: app
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
    depends_on:
      - db
